org.gradle.jvmargs=-Xmx2G

org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.vfs.watch=false
org.gradle.workers.max=2

android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.newDsl=false

kotlin.parallel.tasks.in.project=false
kotlin.incremental=false

android.disableDexingArtifactTransform=true

org.gradle.projectcachedir=../.gradle-local